---
title: "No Evidence of Discrimination Accessing COVID-19 Immunization Clinics Across the City of Toronto"
author: "Bolin Shen"
format: pdf
---


```{r}
#| message: false
#| echo: false

#### Workspace set-up ####

## Load packages
library(tidyverse)
library(knitr)
library(janitor)
library(here)
library(dplyr)

#### Read in cleaned data ####

cleaned_poll_data = read_csv(
  file = here("input/data/cleaned_poll_data.csv"),
  show_col_types = FALSE
)


```





```{r}
ggplot(mapping = aes(x = application_for, fill = response_rate_met), data = cleaned_poll_data) + 
  scale_fill_discrete(name = "response rate met") + ylab("Number of polls") + xlab("Application for") + geom_bar() + 
  theme(axis.text.x= element_text(angle= 50, vjust=0.8, hjust= 0.8))
```

```{r}
ggplot(mapping = aes(x = application_for, fill = poll_result), data = cleaned_poll_data) + geom_bar() +
  theme(axis.text.x= element_text(angle= 50, vjust=0.8, hjust= 0.8)) + xlab("Application for") + ylab("Number of polls") + 
  scale_fill_discrete(name = "Poll result")
```
```{r}
traffic_calming <- cleaned_poll_data[cleaned_poll_data$application_for == 'Traffic Calming',]
middle <- median(traffic_calming$ballots_distributed)
traffic_calming <- traffic_calming[traffic_calming$ballots_distributed > middle, ]

front_yard_parking <- cleaned_poll_data[cleaned_poll_data$application_for == 'Front Yard Parking',]
middle <- median(front_yard_parking$ballots_distributed)
front_yard_parking <- front_yard_parking[front_yard_parking$ballots_distributed > middle, ]

permit_parking <- cleaned_poll_data[cleaned_poll_data$application_for == 'Permit Parking',]
middle <- median(permit_parking$ballots_distributed)
permit_parking <- permit_parking[permit_parking$ballots_distributed > middle, ]

print(traffic_calming)
print(front_yard_parking)
print(permit_parking)

traffic_calming |>
  ggplot(aes(x = open_date, y = ballot_return_rate)) +
  labs(x = "Date",
       y = "ballot return rate",
       caption = "TBD") +
  geom_line() + 
  theme_minimal()

front_yard_parking |>
  ggplot(aes(x = open_date, y = ballot_return_rate)) +
  labs(x = "Date",
       y = "ballot return rate",
       caption = "TBD") +
  geom_line() + 
  theme_minimal()

permit_parking |>
  ggplot(aes(x = open_date, y = ballot_return_rate)) +
  labs(x = "Date",
       y = "ballot return rate",
       caption = "TBD") +
  geom_line() + 
  theme_minimal()
```


```{r}
traffic_calming <- cleaned_poll_data[cleaned_poll_data$application_for == 'Traffic Calming',]
middle <- median(traffic_calming$ballots_cast)
traffic_calming <- traffic_calming[traffic_calming$ballots_cast > middle, ]

front_yard_parking <- cleaned_poll_data[cleaned_poll_data$application_for == 'Front Yard Parking',]
middle <- median(front_yard_parking$ballots_cast)
front_yard_parking <- front_yard_parking[front_yard_parking$ballots_cast > middle, ]

permit_parking <- cleaned_poll_data[cleaned_poll_data$application_for == 'Permit Parking',]
middle <- median(permit_parking$ballots_cast)
permit_parking <- permit_parking[permit_parking$ballots_cast > middle, ]

print(traffic_calming)
print(front_yard_parking)
print(permit_parking)

traffic_calming |>
  ggplot(aes(x = open_date, y = ballot_in_favour_rate)) +
  labs(x = "Date",
       y = "ballot opposed rate",
       caption = "TBD") +
  geom_line() + 
  theme_minimal()

front_yard_parking |>
  ggplot(aes(x = open_date, y = ballot_in_favour_rate)) +
  labs(x = "Date",
       y = "ballot o rate",
       caption = "TBD") +
  geom_line() + 
  theme_minimal()

permit_parking |>
  ggplot(aes(x = open_date, y = ballot_in_favour_rate)) +
  labs(x = "Date",
       y = "ballot return rate",
       caption = "TBD") +
  geom_line() + 
  theme_minimal()
```
